version: "1.27.0"
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=next_auth_prisma_ecconnect_db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres-data:
