version: "1.27.0"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "6500:5432"
volumes:
  postgres:
# DATABASE_URL="postgresql://postgres:postgres@localhost:5432:5432/next_auth_prisma_ecconnect_db?schema=public"n
