import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { Avatar, Badge, Link } from "@nextui-org/react";
import { GiWaterDrop } from "react-icons/gi";
import prisma from "@/app/lib/prisma";
import { Friend } from "@/app/types/db";
import { getUserContent } from "@/app/helpers/getUser";
import Messages from "../../components/Messages";
import UserPicture from "../../components/UserPicture";
import Search from "../../components/Search";
import SignOutButton from "../../components/SignOutButton";

interface LayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = async ({ children }) => {
  const session = await getServerSession(options);
  if (!session) return;

  const userInfo = await getUserContent(session.user.id);

  const userRole = userInfo.role as string;

  const getFriends = await prisma.user.findMany({
    where: {
      id: session.user.id,
    },
    select: {
      friends: true,
    },
  });

  const friendsList = getFriends[0].friends as unknown as Friend[];

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen overflow-clip">
          <div className="sticky bg-zinc-100 h-20 w-screen flex items-center px-6 gap-4 rounded-md shadow-lg backdrop-blur-md">
            <div className="w-1/6 flex gap-2">
              <Link
                href={"/employer-dashboard"}
                className="flex gap-4 text-blue-800"
              >
                <GiWaterDrop />
                <p className="hidden md:flex font-bold text-inherit">
                  Econnect
                </p>
              </Link>
            </div>
            <div className="w-5/6 hidden md:flex gap-2 justify-end">
              <Search />
              <UserPicture />
              <SignOutButton />
            </div>
          </div>
          <div className="w-1/4 absolute">
            <Messages userId={session?.user.id} friends={friendsList} />
          </div>
          <aside>{children}</aside>
          <div className="fixed bottom-0 right-0 p-8 flex flex-col gap-5">
            {/* <NewPost /> */}
          </div>
        </div>
      </body>
    </html>
  );
};

export default Layout;
