import type { Metadata } from "next";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { FunctionComponent, ReactNode } from "react";
import { getServerSession } from "next-auth";
import { notFound } from "next/navigation";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";

interface LayoutProps {
    children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Layout: FunctionComponent<LayoutProps> = async ({ children }) => {
    const session = await getServerSession(options);
    if (!session) notFound();

    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
};

export default Layout;
