import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Navbar from "@/app/(protected)/components/Navbar";
import Messages from "../components/Messages";

interface LayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  // You can move the session logic to a useEffect or similar if needed
  return (
    <html lang="en">
      {/* Your layout content */}
      <body className={inter.className}>
        <Navbar />
        <aside>{children}</aside>
        <div className="fixed bottom-0 right-0 p-8 flex flex-col gap-5">
          {/* <NewPost /> */}
          <Messages />
        </div>
      </body>
    </html>
  );
};

export default Layout;
