import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Navbar from "@/app/(protected)/components/Navbar";
import Messages from "../components/Messages";
import { getServerSession } from "next-auth";
import { options } from "@/app/api/auth/[...nextauth]/options";
import axios from "axios";
import { pusherClient } from "@/app/lib/pusher";
import { toPusherKey } from "@/app/lib/utils";
import { Message } from "postcss";

interface LayoutProps {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = async ({ children }) => {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      {/* Your layout content */}
      <body className={inter.className}>
        <div className="h-screen w-screen overflow-clip">
          <Navbar />
          <aside>{children}</aside>
          <div className="fixed bottom-0 right-0 p-8 flex flex-col gap-5">
            {/* <NewPost /> */}
          </div>
        </div>
      </body>
    </html>
  );
};

export default Layout;
